import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createGroupProject,applyContribution,encodeGroupShare} from '../src/group-project-engine.js';
import {loadCommunityWorld} from '../src/gifts.js';
import {decodeGiftProject,giftHomeURL,setupGiftPreview} from '../src/home-gift-preview.js';
const base=new URL('../',import.meta.url);
const community=()=>loadCommunityWorld(readFileSync(new URL('community/world.json',base),'utf8'),{'community/gifts/welcome-planter.json':readFileSync(new URL('community/gifts/welcome-planter.json',base),'utf8')});
function completed(){let p=createGroupProject({seed:'controller'});for(const[id,action]of[[p.participants[0].id,{type:'movement',gait:'hop'}],[p.participants[1].id,{type:'rhythm',rhythm:[1,0,1,0,1,0,1,0]}],[p.participants[2].id,{type:'harmony',harmony:'moonlight',timbre:'bell'}]])p=applyContribution(p,id,action);return p;}
function harness({hash='',stored=null,denySave=false,denyRemove=false,world=community()}={}){
 const nodes=new Map(),events={},changes=[],storage=new Map(),location=new URL('https://example.github.io/home/'+hash),key='dot.local-garden-gift.v1:/home/';if(stored)storage.set(key,stored);
 const get=id=>{if(!nodes.has(id))nodes.set(id,{hidden:true,dataset:{},textContent:'',listeners:{},addEventListener(name,fn){this.listeners[name]=fn;},focus(){}});return nodes.get(id);};
 const saved={};for(const name of['document','window','location','history','localStorage'])saved[name]=Object.getOwnPropertyDescriptor(globalThis,name);
 const globals={document:{getElementById:get,body:{dataset:{}}},window:{addEventListener:(name,fn)=>{events[name]=fn;}},location,history:{replaceState(_a,_b,url){location.href=new URL(url,location).href;}},localStorage:{getItem:k=>storage.get(k)||null,setItem(k,v){if(denySave)throw Error('Denied');storage.set(k,v);},removeItem(k){if(denyRemove)throw Error('Denied');storage.delete(k);}}};
 for(const[name,value]of Object.entries(globals))Object.defineProperty(globalThis,name,{value,configurable:true});
 const controller=setupGiftPreview({community:world,homeContext:{links:{contribute:'https://github.com/example/home/blob/main/CONTRIBUTING.md'}},onChange:(...args)=>changes.push(args)});
 return{controller,get,storage,key,changes,events,location,dispose(){for(const[name,descriptor]of Object.entries(saved))descriptor?Object.defineProperty(globalThis,name,descriptor):delete globalThis[name];}};
}
test('gift URL is same-home, bounded and retains only a valid release hint',()=>{const p=completed();const url=new URL(giftHomeURL(p,'https://friend.github.io/own/group.html?v=abcdef123&other=secret'));assert.equal(url.pathname,'/own/');assert.equal(url.search,'?v=abcdef123');assert.equal(decodeGiftProject(url.hash.slice(14)).id,p.id);assert.throws(()=>decodeGiftProject('x'.repeat(17000)));assert.throws(()=>decodeGiftProject(encodeGroupShare(createGroupProject())));});
test('local display is explicit and never mutates the accepted community',()=>{const p=completed(),encoded=encodeGroupShare(p),s=harness({hash:'#gift-project='+encoded});try{assert.equal(s.controller.active,true);assert.equal(s.controller.community.placements.length,2);assert.equal(community().placements.length,1);assert.equal(s.storage.size,0);s.get('save-local-gift').listeners.click();assert.equal(s.storage.get(s.key),encoded);s.get('remove-local-gift').listeners.click();assert.equal(s.controller.active,false);assert.equal(s.controller.community.placements.length,1);assert.equal(s.storage.size,0);assert.equal(s.location.hash,'');assert.equal(s.changes.at(-1)[1],false);}finally{s.dispose();}});
test('denied storage does not claim persistence and denied removal warns about reload',()=>{const encoded=encodeGroupShare(completed());let s=harness({hash:'#gift-project='+encoded,denySave:true});try{s.get('save-local-gift').listeners.click();assert.match(s.get('local-gift-message').textContent,/only in this tab/);assert.equal(s.storage.size,0);}finally{s.dispose();}s=harness({stored:encoded,denyRemove:true});try{assert.equal(s.controller.active,true);s.get('remove-local-gift').listeners.click();assert.equal(s.controller.active,false);assert.equal(s.get('gift-preview-error').hidden,false);assert.match(s.get('gift-preview-error').textContent,/may return after reload/);assert.equal(s.storage.get(s.key),encoded);}finally{s.dispose();}});
test('malformed hashes, corrupt saves and unavailable gardens fail closed',()=>{for(const options of[{hash:'#gift-project=bad'},{stored:'bad'},{hash:'#gift-project='+encodeGroupShare(completed()),world:null}]){const s=harness(options);try{assert.equal(s.controller.active,false);assert.equal(s.get('local-gift-preview').hidden,true);}finally{s.dispose();}}});
test('new invalid hash clears a local display but keeps the accepted scene',()=>{const s=harness({hash:'#gift-project='+encodeGroupShare(completed())});try{s.location.hash='#gift-project=bad';s.events.hashchange();assert.equal(s.controller.active,false);assert.equal(s.controller.community.placements.length,1);assert.equal(s.changes.at(-1)[1],false);assert.equal(s.get('gift-preview-error').hidden,false);}finally{s.dispose();}});
