import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {STATES,validateStatus,statusAge} from '../src/state.js';
import {resolveHomeContext} from '../src/home.js';
const configuredHome=JSON.parse(readFileSync(new URL('../home.json',import.meta.url),'utf8'));
const homeConfig=JSON.parse(readFileSync(new URL('./fixtures/reference-home.json',import.meta.url),'utf8'));
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
const code=readFileSync(new URL('../src/main.js',import.meta.url),'utf8').replace(/^import .*\n/gm,'').replaceAll('import.meta.env.BASE_URL',JSON.stringify('./'));
const tick=()=>new Promise(resolve=>setImmediate(resolve));
async function setup({delayFirstFeed=false,repository='mzbac/dots',hostname='mzbac.github.io',pathname='/dots/',ownerRepository='mzbac/dots',settings=homeConfig}={}){
 const elements=new Map();const make=id=>({id,tagName:'DIV',dataset:{},hidden:false,firstElementChild:{},listeners:{},addEventListener(name,fn){this.listeners[name]=fn;},attrs:{},setAttribute(name,value){this.attrs[name]=value;},getAttribute(name){return this.attrs[name]??null;},showModal(){},close(){},getBoundingClientRect(){return{};}});
 const get=id=>{if(!elements.has(id))elements.set(id,make(id));return elements.get(id);};
 const buttons=Object.keys(STATES).map(state=>({...make(state),tagName:'BUTTON',dataset:{state}}));
 const doc={hidden:false,body:{dataset:{}},getElementById:get,querySelectorAll:()=>buttons,listeners:{},addEventListener(name,fn){this.listeners[name]=fn;}};
 const appliedStates=[];let releaseFirstFeed;const firstFeed=new Promise(resolve=>{releaseFirstFeed=resolve;});
 const requests=[];let value={schemaVersion:1,ownerRepository,state:'checking',revision:2,updatedAt:'2026-09-30T09:21:51Z'};let interval;
 await new AsyncFunction('STATES','validateStatus','statusAge','createWorkshop','document','matchMedia','fetch','setInterval','location','resolveHomeContext','homeConfig','__HOME_REPOSITORY__','loadAcceptedCommunity','createGardenCells','drawGardenStill','setupGiftPreview',code)(STATES,validateStatus,statusAge,async()=>({setState(state){appliedStates.push(state);},setPaused(){},setInteractive(){},setView(){}}),doc,()=>({matches:false,addEventListener(){}}),async(url,options)=>{requests.push({url,options});if(delayFirstFeed&&requests.length===1)await firstFeed;return{ok:true,json:async()=>value};},fn=>{interval=fn;},{hostname,pathname},resolveHomeContext,settings,repository,()=>{throw new Error('No gift fixture');},()=>[],()=>{},({community})=>({community,active:false}));
 await tick();return{get,buttons,doc,requests,appliedStates,releaseFirstFeed:async()=>{releaseFirstFeed();await tick();},set:valueNew=>{value={ownerRepository,...valueNew};},poll:async()=>{interval();await tick();}};
}
test('the checked-in home refreshes only its own validated published feed',async()=>{const [owner,name]=configuredHome.ownerRepository.split('/'),hostname=`${owner.toLowerCase()}.github.io`;const s=await setup({settings:configuredHome,repository:configuredHome.ownerRepository,ownerRepository:configuredHome.ownerRepository,hostname,pathname:name.toLowerCase()===hostname?'/':`/${name}/`});assert.deepEqual(s.appliedStates,['checking']);assert.equal(s.requests.length,1);assert.equal(s.requests[0].url.split('?')[0],`https://raw.githubusercontent.com/${configuredHome.ownerRepository}/${configuredHome.status.branch}/public/status.json`);});
test('a configured second-account home accepts its own feed and rejects a copied upstream payload',async()=>{const settings={...homeConfig,ownerRepository:'mzbacd/dots',name:'dot Test Home',characterPalette:'seafoam'},runtime={settings,repository:'mzbacd/dots',hostname:'mzbacd.github.io',pathname:'/dots/'};const own=await setup({...runtime,ownerRepository:'mzbacd/dots'});assert.deepEqual(own.appliedStates,['checking']);assert.equal(own.requests[0].url.split('?')[0],'https://raw.githubusercontent.com/mzbacd/dots/main/public/status.json');const copied=await setup({...runtime,ownerRepository:'mzbac/dots'});assert.equal(copied.requests.length,1);assert.deepEqual(copied.appliedStates,[]);assert.equal(copied.get('status-source').textContent,'MOOD UNAVAILABLE');});
test('visible Pages view refreshes from the public repository without reload',async()=>{const s=await setup();assert.equal(s.get('state-title').textContent,'A closer look');s.set({state:'waiting',revision:3,updatedAt:'2026-09-30T09:28:54Z'});await s.poll();assert.equal(s.get('state-title').textContent,'Room to breathe');assert.equal(s.requests.length,2);assert.match(s.requests[1].url,/^https:\/\/raw\.githubusercontent\.com\/mzbac\/dots\/main\/public\/status\.json\?v=\d+$/);assert.equal(s.requests[1].options.cache,'no-store');});
test('visitors have no mood selectors or state override controls',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.doesNotMatch(html,/state-option|return-button|preview-label|Every state has a spark/);assert.doesNotMatch(code,/URLSearchParams|location.search|isPreview/);});
test('hidden pages pause polling and refresh when shown',async()=>{const s=await setup();s.doc.hidden=true;await s.poll();assert.equal(s.requests.length,1);s.doc.hidden=false;s.doc.listeners.visibilitychange();await tick();assert.equal(s.requests.length,2);});

test('a delayed first feed does not apply an invented resting action',async()=>{const s=await setup({delayFirstFeed:true});assert.equal(s.requests.length,1);assert.deepEqual(s.appliedStates,[],'No public action should be applied before the first real feed');await s.releaseFirstFeed();assert.deepEqual(s.appliedStates,['checking']);assert.equal(s.get('state-title').textContent,STATES.checking.title);});

test('an unconfigured fork never requests or applies an inherited mood',async()=>{const s=await setup({repository:'friend/dots',hostname:'friend.github.io'});assert.equal(s.requests.length,0);assert.deepEqual(s.appliedStates,[]);assert.equal(s.get('updated-at').textContent,'No mood shared yet');});
test('a public feed belonging to another home is not applied',async()=>{const s=await setup({ownerRepository:'friend/dots'});assert.equal(s.requests.length,1);assert.deepEqual(s.appliedStates,[]);assert.equal(s.get('status-source').textContent,'MOOD UNAVAILABLE');});
